services:
  mongo:
    image: "mongo:5.0.2"
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dbpass
  mongo-express:
    image: "mongo-express:0.54.0"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: dbpass
      ME_CONFIG_MONGODB_URL: mongodb://root:dbpass@mongo:27017/
    links:
      - "mongo"
volumes:
  mongodata: {}